<Digit> ::= [0-9]
<Integer> ::= <Digit>*
<Alpha> ::= [a-zA-Z]
<Character> ::= <Integer> | <Alpha>
<String> ::= <Character>*
<Boolean> ::= 'true' | 'false'

<Comparison> ::= '==' | '!=' | '>' | '<' | '>=' | '<='
<BooleanOperator> ::= '&&' | '||' | '!'
<NumericalOperator> ::= '+' | '-' | '*' | '/' | '%' | '^'
<Operator> ::= <BooleanOperator> | <NumericalOperator>

<Item> ::= Subj | Obj | Pred | <Item>*
<File> ::= <String>'.'<String>
<Predicate> ::= <Item><Comparison><String> | <Item><Comparison><Reference> | <Predicate><BooleanOperator><Predicate>

<Query> ::= 'SELECT' <Item> 'FROM' <File> 'WHERE' <Predicate> | 'SELECT' <Item> 'FROM' <File>
<Exp> ::= 'OUT' <Variable> | <VariableAssignement>

<Variable> ::= <Alpha><String>
<Value> ::= <Query> | <String> | <Integer> | <Boolean> | <Variable>
<Modifer> ::= <Operator><Value>
<VariableAssignement> ::= <Variable>'='<Value><Modifer>*
<Reference> ::= <Variable>'.Subj' | <Variable>.'Obj' | <Variable>.'Pred'
