<Digit> ::= [0-9]
<Integer> ::= <Digit>*
<Alpha> ::= [a-zA-Z]
<Character> ::= <Integer> | <Alpha>
<String> ::= <Character>*
<Boolean> ::= 'true' | 'false'

<Comparison> ::= '==' | '!=' | '>' | '<' | '>=' | '<='
<BooleanOperator> ::= '&&' | '||' | '!'
<NumericalOperator> ::= '+' | '-' | '*' | '/' | '%' | '^'
<Operator> ::= <BooleanOperator> | <NumericalOperator>

<Item> ::= Subj | Obj | Pred | <Item>*
<File> ::= <String>'.'<String>
<Predicate> ::= <Item><Comparison><String> | <Item><Comparison><Reference> | <Predicate><BooleanOperator><Predicate>

<Query> ::= 'SELECT' <Item> 'FROM' <File> 'WHERE' <Predicate> 'ORDERBY' <Item> | 'SELECT' <Item> 'FROM' <File> 'WHERE' <Predicate> | 'SELECT' <Item> 'FROM' <File>
<Exp> ::= <Query> | 'CREATE' <File> | 'INSERT' <Query> 'INTO' <File> | <VariableAssignement>

SELECT Pred FROM foo.ttl WHERE Subj == "testSubA"

<Identifier> ::= <Alpha><String>
<Value> ::= <Query> | <String> | <Integer> | <Boolean>
<Modifer> ::= <Operator><Value>
<Variable> ::= <Identifier>
<VariableAssignement> ::= <Variable>'='<Value><Modifer>*
<Referencable> ::= <File> | <Variable>
<Reference> ::= <Referencable>'.Subj' | <Referencable>.'Obj' | <Referencable>.'Pred'
